- .eslintrc.js
- docs/.eslintrc.js
- docs/package.json
- package.json
- yarn.lock
- Update ESLint packages
- Set up root level `.eslintrc.js` file (heavily inspired by [this one](https://github.com/keystonejs/keystone/blob/main/.eslintrc.js))
- Remove seperate `.eslintrc.js` file in Next app
- Update lint scripts to use `.gitignore` for ignore path
> Review and update ESLint rules

- docs/components/mdx-components/react-live.tsx
Updates the `Open in Playroom` and `Copy Code` buttons to use the `ButtonLink` and `Button` component respectively.
> Swap out hand-rolled buttons in code example

- .changeset/config.json
- .changeset/plenty-apricots-give.md
- babel.config.json
- package.json
- yarn.lock
The SSR package was trying to use a global (`regeneratorRuntime`) which wasn't being defined:
[@babel/plugin-transform-runtime](https://babel.dev/docs/en/babel-plugin-transform-runtime#regenerator) adds this for us automatically (and it also claims to help reduce bundle size).
I've tested this locally and it seems to be working as expected.
I've also bumped the versions of our packages since Babel (which Preconstruct runs on all of our packages to create the builds) will output slightly different code now that we're using the transform runtime plugin.
> Add @babel/plugin-transform-runtime

- package.json
If you have a folder in the `packages` directory without a `package.json` or `README.md` the docs will fail to build. This happens to me all the time when switching between feature branches.
Running `yarn clean:packages` will delete all the temporary files in that directory. You can then run `yarn && yarn start` to start the docs.
We also generate a lot of assets inside the `docs` directory (`.next` folder as well as Storybook and Playroom).
Running `yarn clean:docs` will delete all the temporary files in the docs directory.
Sometimes you just want to delete _all_ the temporary files. In that case you can run `yarn clean:write`.
> Add clean scripts

- .editorconfig
- .vscode/extensions.json
- .vscode/settings.json.example
Add VSCode workspace extensions and recommended settings.
Mostly the same as what we had in the energy monorepo, lightly edited with some settings that I've found to be more reliable ([borrowed from here](https://github.com/wesbos/eslint-config-wesbos#with-vs-code)).
> Add VSCode workspace settings

- .changeset/seven-suns-explode.md
- packages/spinner/src/Spinner.tsx
At the moment, the spinner disappears on the 100% keyframe. I’d like to retain a piece of the circle so that the spinner never completely disappears as it loops.
> Patch for loader animation

- package.json
Fixes the `clean:docs` and `clean:packages` scripts not working properly. Before if you tried to run them you'd get the following error:
`error Command "git" not found.`
> Fix clean scripts

- packages/float-input/README.md
- packages/text-input/README.md
Float input currently supports input adornments by passing in a children prop, but the behaviour is currently undocumented. This PR documents that behaviour.
> docs: added input adornment section for float input component docs

- docs/pages/package/[slug].tsx
We had two links that would do the same thing: "Open in GitHub" and "Source".
This PR replaces the "Open in GitHub" link with one to edit the current page.
> Replace "Open in GitHub" link with "Edit this page"

- docs/components/example-helpers.tsx
- docs/components/layout.tsx
- docs/components/mdx-components/mdx-components.tsx
- docs/components/mdx-components/mdx-table.tsx
- docs/components/mdx-components/react-live.tsx
- docs/components/sidebar.tsx
- docs/playroom/frame.tsx
- packages/a11y/src/idContext.tsx
- packages/accordion/src/Accordion.tsx
- packages/alert/src/Alert.tsx
- packages/button/src/Button.tsx
- packages/control-label/src/control-label.tsx
- packages/dropzone/src/dropzone.tsx
- packages/modal-dialog/src/content-dialog.tsx
- packages/select/src/Select.tsx
- packages/utils/src/ts/forwardRefWithAs.ts
- packages/utils/src/ts/utility-types.ts
When Spark Web was in the energy monorepo, we had to use the Babel and ESLint configs that were already there. Neither was configured to let you omit the React import for hinting to Babel/SWC to use `React.createElement` on JSX.
Now that we've got a bit more control this has been fixed. We did a big pass of the codebase when we pulled it out so that we could tree-shake React code from the packages, but missed a few places. This is just finishing that work off.
> Update React imports

- docs/components/mdx-components/mdx-content.tsx
- docs/contentlayer.config.ts
- docs/package.json
- docs/pages/index.tsx
- docs/pages/package/[slug].tsx
- yarn.lock
By specifying the `contentType` as `mdx` in `contentlayer.config.ts` we can remove all the manual MDX Bundler setup.
I've also included the `useLiveReload` hook which provides live reloading of our MDX content to improve DX when writing docs.
Finally I've added `onUnknownDocuments: 'skip-ignore'` to on Contentlayer config so to hide the warning about extra files being in the directories that Cotentlayer looks in to generate our docs.
> Remove manual MDX bundler setup

- CONTRIBUTING.md
- README.md
Adding in contributing docs that were drafted in our Confluence, it's not finalised by worthwhile for new contributors to have access to.
> Add in Contributing Docs

- .changeset/afraid-worms-tap.md
- packages/text-input/src/InputAdornment.tsx
> Fix alignment of icon adornments

- .changeset/angry-boats-cough.md
- packages/combobox/src/combobox.tsx
- packages/select/src/Select.tsx
- packages/text-input/src/TextInput.tsx
The `FieldContext` provides an invalid boolean.
Currently this is only being used for styling. This PR uses it to mark the components that consume this context as invalid.
> Add aria-invalid attribute to field items

- docs/components/content/toc-context.tsx
- docs/components/mdx-components/mdx-components.tsx
- docs/contentlayer.config.ts
- docs/pages/_app.tsx
- docs/pages/index.tsx
- docs/pages/package/[slug].tsx
- docs/tsconfig.json
When we added the path alias for contentlayer to our tsconfig it made it so that automatic imports from VSCode were no longer relative.
This makes it less clear if an import is a local file or an installed dependency and leads to inconsistent imports.
> Remove baseUrl and paths from docs tsconfig

- .changeset/slimy-spiders-sell.md
- packages/text-input/src/TextInput.tsx
Change `<TextInput/>` native prop types to match `<input/>`
> Fix TextInput type

- .changeset/empty-birds-flash.md
- .changeset/three-squids-accept.md
- .changeset/tiny-bananas-doubt.md
- packages/a11y/src/focusRing.ts
- packages/select/src/Select.tsx
- packages/text-area/src/text-area.tsx
- packages/text-input/src/TextInput.tsx
- packages/text-input/src/index.ts
One thing that we considered when designing our inputs is that password managers like to insert their icons _inside_ of the inputs. This can overlap with adornments (buttons/icons etc) so we are careful to wrap our inputs in an element that wraps both the input and adornments and fakes the focus ring. This way the input sits beside the adornment instead of of the adornment being absolutely positioned above the input.
Previously we were using the :focus-within` pseudo-class to apply the focus ring to the wrapper div whenever any child had focus, however, this causes double focus rings when we focus on the adornment (for things like the [PasswordInput](https://github.com/brighte-labs/spark-web/pull/90)).
The way I've come up with to address this is to stop using `:focus-within` and instead …
> Update focus and disabled styles for form elements

- .changeset/mighty-kiwis-reply.md
- .changeset/three-tomatoes-kick.md
- packages/combobox/src/combobox.tsx
- packages/currency-input/src/CurrencyInput.tsx
- packages/dropzone/src/dropzone.tsx
- packages/field/src/Field.tsx
- packages/field/src/context.ts
- packages/field/src/index.ts
- packages/select/src/Select.test.tsx
- packages/select/src/Select.tsx
- packages/text-area/src/text-area.tsx
- packages/text-input/src/TextInput.tsx
This PR addresses some feedback from Joss:
https://github.com/brighte-labs/spark-web/pull/101#discussion_r876582101
It refactors the `useFieldContext` hook to return a tuple of state and derived props and adds `aria-invalid`.
> Refactor useFieldContext to return tuple

- packages/password-input/src/PasswordInput.tsx
- packages/text-input/README.md
- packages/text-input/src/InputContainer.tsx
- packages/text-input/src/TextInput.tsx
- packages/text-input/src/index.ts
This PR moves the `InputContainer` into it's own file and adds docs for what it is, and how to use it.
I haven't added a changeset for this, as it will just add noise to the changelog (since we haven't published a release since the `InputContainer` was added). The API hasn't changed, so it would just be a patch.
> Move InputContainer to it's own file and document it

- packages/text-input/README.md
- packages/text-input/src/InputContainer.tsx
Fixes the table formatting and adds descriptions for the InputContainer: 
https://spark.brighte.com.au/package/text-input#inputcontainer-1
Don't think it needs a changeset since we haven't published since the InputContainer was added yesterday...
> Update InputContainer docs

- .changeset/short-brooms-kneel.md
- packages/combobox/README.md
- packages/combobox/src/combobox.tsx
- packages/combobox/src/react-select-overrides.tsx
Expose combobox `isLoading` prop from `react-select` to manually control loading status
> feat(combobox): expose isLoading prop

- .changeset/rotten-monkeys-smash.md
- packages/fieldset/package.json
- packages/fieldset/src/fieldset.tsx
Fieldset has a `gap` prop, but it's only used for the gap between the legend and the content.
This PR adds a Stack to control space between the `children`.
If users require different spacing between `children` for they can wrap their children in another `Stack`, but this should provide a sensible default.
> Control spacing of Fieldset children

- .changeset/two-islands-fold.md
- packages/field/src/Field.tsx
I noticed that the spacing in our field could use tightening up a little as Capsize wasn't controlling the line-height of the label.
Removing the `inline` prop from this element brought things a lot closer together so I've also bumped up the spacing of the Stack responsible for the vertical spacing to account for it.
Before (notice the extra space on the label and adornment row):
After:
> Tighten up spacing for Field

- packages/field/src/Field.tsx
After merging [this PR](https://github.com/brighte-labs/spark-web/pull/123), I noticed that the `reserve-space` prop was now reserving the wrong amount of space. This PR fixes that.
Before:
After:
Changes are already covered by this changeset:
https://github.com/brighte-labs/spark-web/blob/main/.changeset/two-islands-fold.md
> Fix the `reserve-space` prop reserving the wrong amount of space

- .changeset/pretty-cheetahs-remain.md
- packages/core/src/fonts.tsx
- packages/core/src/index.ts
Once the CORS issues are fixes, we can load fonts from the Brighte subdomain. Until then I'm leaving this PR open.
> Load fonts from Brighte subdomain

- .changeset/lovely-dryers-argue.md
- packages/field/src/Field.tsx
[Joss pointed out](https://brighte-au.slack.com/archives/C03C4J5AUHY/p1653353190316019) that the gap property was collapsing in certain scenarios.
This is because the gap was being set to `undefined` if the `labelVisibility` was set to "hidden". We did this because the Box that wraps the label was still appearing in the DOM, and the gap prop was causing space to be reserved for this hidden element (forgetting that the gap was needed for the description and message to be spaced properly.
In my testing, it looks like we can wrap the label with a fragment if labelVisibility is hidden, as Flexbox is smart enough to not reserve space for the `VisuallyHidden` label (I tested this in Brave (Chromium), Firefox and Safari).
- [SPRK-92](https://brighte.atlassian.net/browse/SPRK-92)
> Fix collapsing gap on Stack in Field

- .changeset/forty-shoes-wave.md
- packages/fieldset/src/fieldset.tsx
This PR updates the Fieldset `<legend>` to have the same treatment as [our updated Field `<labels>`](https://github.com/brighte-labs/spark-web/pull/123).
Before:
After:
> Remove inline from Legend

- docs/.env.development
Previously, when running the docs in development mode, Storybook and Playroom links, would link to the deployed site to ensure that you could always get to them.
In practice this wasn't very useful when you were trying to test things locally. So I've updated the links to point to their local servers instead.
> Update Playroom and Storybook dev env vars

- .changeset/wet-rivers-sell.md
- packages/combobox/README.md
- packages/combobox/package.json
- packages/combobox/src/combobox.test.tsx
- packages/combobox/src/combobox.tsx
- packages/combobox/src/react-select-overrides.tsx
Shout out to @lukebennett88 who did 99% of the hard yards on this PR. Basically schooled me! bahaha!
Combobox now passes through aria props from wrapper field component to the ReactSelect Input element. 
Combobox now passes through data attributes passed into the component in line with other components in the Lib
- SPRK-83
- SPRK-84
> Pass through data-attributes and a11y props to underlying input in Combobox

- .changeset/beige-otters-lick.md
- packages/spinner/README.md
- packages/spinner/src/Spinner.test.tsx
- packages/utils/src/use-synchronized-animation.ts
There was a bug in the `useSynchronizedAnimation` that was picked up in a test:
Looks like `animationTarget` could potentially be undefined, so this PR adds a guard, as well as updates our tests and some minor docs fixes that I picked up while looking at the `Spinner`.
Note: none of the code for the `Spinner` itself has been changed (just docs and test) so it's just the `utils` that has a changelog.
> Check for `animationTarget` in `useSynchronizedAnimation`

- docs/next.config.mjs
We're currently seeing a bunch of Webpack `PackFileCacheStrategy` warnings:
This adds a lot of noise to the console, making it hard to find what you're looking for.
This started happening after adding [Contentlayer](https://www.contentlayer.dev/), and the warnings themselves also reference Contentlayer.
For the time being, I'm proposing we suppress these warnings as it seems to be an issue with Webpack itself:
https://github.com/vercel/next.js/discussions/30870#discussioncomment-1862620
> Suppress Webpack `PackFileCacheStrategy` warnings

- .changeset/curvy-ducks-appear.md
- packages/password-input/src/IconButton.tsx
Clicking the show/hide button in the PasswordInput will submit the form as a button defaults to `type="submit"`.
Adding `type="button"` fixes this.
> Add type="button" to `IconButton`

- .changeset/thirty-eels-perform.md
- packages/spinner/package.json
- packages/spinner/src/Spinner.test.tsx
- packages/spinner/src/Spinner.tsx
Currently, in test we have no way to tell whether the app is in a loading state.
Make Spinner accessible so that we can wait for it to disappear.
- [x ] I've updated unit tests where needed
- [x ] I've updated the components README.md where needed
- [x ] I've added major version bumps for my breaking changes
- [x ] I've added changesets where needed
- [x ] All the components I've updated are reflected in the changelog
> feat(spinner): make spinner accessible

- .changeset/neat-pumpkins-grab.md
- .changeset/tough-spies-wink.md
- packages/row/src/Row.tsx
Adds prop spreading back to `Row` that was removed [here](https://github.com/brighte-labs/spark-web/pull/99).
Layout primitive will need to keep the spread as they are polymorphic, so the valid props will vary depending on what the `as` prop is.
Before:
After:
> Add spread back to Row

- .changeset/rich-cycles-rush.md
- packages/button/src/resolveButtonChildren.tsx
I noticed that small icons were slightly misaligned when inside of a button. This PR fixes it!
Before:
After:
> Centre `HiddenWhenLoading` container inside of `Button`

- .changeset/itchy-papayas-divide.md
- packages/columns/src/Columns.tsx
- packages/row/src/Row.tsx
We removed a bunch of instances of prop spreading in <https://github.com/brighte-labs/spark-web/pull/99>.
I'm a little unsure about removing `className` and `style` props as there are valid use cases for them at the moment (e.g. with the `Stack` component in the docs, [we set an arbitrary width using `style`](https://spark.brighte.com.au/package/text#overflow-strategy)).
Whilst it's not recommended to use these props if you can help it, sometimes they are the lesser of two evils!
> Add className and style back to layout primitives

- .changeset/ninety-cows-call.md
- packages/password-input/src/IconButton.tsx
- packages/password-input/src/PasswordInput.tsx
The IconButton only has an icon inside it, so there was no way for screen readers to know what the button did.
This PR adds an aria-label to fix it!
> Add aria-label to IconButton

- .changeset/breezy-shirts-live.md
- packages/password-input/src/IconButton.tsx
- packages/password-input/src/PasswordInput.tsx
After reading this article and doing some manual testing with [VoiceOver](https://incl.ca/show-hide-password-accessibility-and-password-hints-tutorial/) there was some some room for improvement with our show/hide password button.
I've added a `role` of `switch` to the button to indicate it toggles between an "on" and "off" state, and changed aria-pressed to aria-checked (as `aria-pressed` and `role="switch"` are incompatible).
> Add role switch and change from aria-pressed to aria-checked

- docs/components/mdx-components/mdx-components.tsx
- docs/components/mdx-components/mdx-content.tsx
- docs/components/mdx-components/props-doc-tables.tsx
- docs/pages/package/[slug].tsx
- packages/button/README.md
- format and sort props data into the shape which is faster in retrieving 
- wrap `PropsTable` inside MDX which offers full flexibility of readme layout
- utilise react context to avoid prop drilling
> Props doc UI

- .changeset/polite-walls-brake.md
- packages/combobox/package.json
- packages/currency-input/package.json
- packages/dropzone/package.json
- packages/float-input/package.json
- packages/password-input/package.json
- packages/select/package.json
- packages/text-area/package.json
- packages/text-input/package.json
Some of our users were getting a bug when they tried to use an input that was wrapped in the Field component.
This was because the inputs had a dependency on `@spark-web/field`, and the version of Field that the inputs were using was different to the version they had installed themselves.
Moving the dependency for Field on these packages into peer-dependencies should fix this.
> Make Field a peer dep to avoid context bug

- .changeset/fuzzy-years-hug.md
- docs/components/mdx-components/props-doc-tables.tsx
- packages/button/README.md
- packages/button/src/BaseButton.tsx
- packages/button/src/Button.tsx
- packages/button/src/index.ts
Inspired by [this PR](https://github.com/steelthreads/agds-next/pull/428) adds a new `BaseButton` component which is an un-styled button that will manually focus the underlying `button` after the user presses it.
The `preventableClickHandler` logic is also move the this component which we then export so other components can potentially use it.
> Create unstyled BaseButton and focus button on click to address Safari bug

- .changeset/shaggy-knives-rescue.md
- packages/text-input/src/TextInput.tsx
Noticed we're not doing anything about text overflow in our inputs. This PR adds text truncation if the text would otherwise overflow its bounding box.
Before:
After:
> Enable text truncation when input value is too long

- docs/components/mdx-components/mdx-components.tsx
- docs/components/mdx-components/mdx-table.tsx
- docs/components/mdx-components/props-doc-tables.tsx
Simplify MDX Table component to enable better props table styling
- Before: https://spark-web-docs-jvuenn6dg-brighte.vercel.app/package/button#button-props
- After: https://spark-web-docs-ihpkr0vb2-brighte.vercel.app/package/button#button-props
> Simplify MDX Table component to enable better props table styling

- .changeset/twelve-apricots-grin.md
- packages/a11y/README.md
- packages/a11y/src/Emoji.tsx
- packages/a11y/src/VisuallyHidden.tsx
This PR adds the `data` prop to `VisuallyHidden` and `Emoji` components for passing along data-attributes to the underlying components.
> Allow `Emoji` and `VisuallyHidden` component to accept data attributes

- .changeset/pink-weeks-hear.md
- packages/control-label/src/control-label.tsx
This is not strictly standard behaviour, but users have been taught that the pointer cursor means that the element below it is interactive.
I spoke with @jordangeizer about this a while back and we decided to adopt this slightly controversial UX.
> Show pointer when hovering over non-disabled label

- .changeset/cuddly-cooks-train.md
- .changeset/nice-dogs-sit.md
- .changeset/wicked-trees-smoke.md
- packages/combobox/src/react-select-overrides.tsx
- packages/select/package.json
- packages/select/src/Select.tsx
- packages/text-area/package.json
- packages/text-area/src/text-area.tsx
- packages/text-area/src/use-text-area.ts
- packages/text-input/src/TextInput.tsx
- packages/text-input/src/index.ts
This PR adds a box shadow to our field inputs, and refactors the `useInput` hook (now renamed to `useInputStyles`) to return a tuple so we can prevent some duplication.
The first item returned from the array is an object containing props that should be spread onto the underlying `Box` element that our inputs are created with, and the second object is a CSS object that should be passed to Emotion's `css` function.
- [SPRK-27](https://brighte.atlassian.net/browse/SPRK-27)
> Update input styles

- .changeset/serious-ants-hide.md
- .changeset/strong-paws-tan.md
- packages/radio/README.md
- packages/radio/package.json
- packages/radio/src/index.ts
- packages/radio/src/radio-card.tsx
- packages/radio/src/radio-primitive.tsx
- packages/radio/src/radio.test.tsx
- packages/radio/src/types.ts
Adds a RadioCard component to `@spark-web/radio`.
As part of this, I've refactored the `RadioPrimitive`.
I've closed my original PR to simplify a few things and will update the `RadioGroup` component in a future PR to address [this issue](https://github.com/brighte-labs/spark-web/issues/15).
- [SPRK-14](https://brighte.atlassian.net/browse/SPRK-14)
> Add RadioCard

- docs/utils/with-search-index.mjs
The `withSearchIndex` script that runs when Next starts was a bit flakey. I'd often get this error:
It seems like there can sometimes be an issue parsing the JSON that is generated by contentlayer. Thankfully contentlayer also generates a `.mjs` file with the same info, so we don't need to parse it.
I tested this locally and couldn't get it to fail.
> Fix search index script

- .changeset/shiny-pumpkins-know.md
- .changeset/tidy-pants-wave.md
- packages/combobox/src/combobox.tsx
- packages/combobox/src/react-select-overrides.tsx
- packages/field/src/Field.tsx
After changing the React Select component overrides to be a function rather than an object in https://github.com/brighte-labs/spark-web/pull/133 we introduced a bug with the [async example in the docs](https://spark-web-docs-git-luke-sprk-84-brighte.vercel.app/package/combobox#async) where you could only type 1 character and then the combobox would stop accepting new user input.
This is because the components were previously created in module scope, but they are now created in function scope, meaning that they are re-created on every render. Memoizing the components helps, but the field context was also not stable so I've _also_ memoized that.
- [SPRK-97](https://brighte.atlassian.net/browse/SPRK-97)
> Fix async combobox bug

- .changeset/nasty-icons-buy.md
- packages/alert/package.json
- packages/alert/src/Alert.test.tsx
- packages/alert/src/Alert.tsx
When the heading prop is omitted, but you have a dismiss button the alignment was all off.
We were also using a hand-rolled button instead of the button component, and some of the colours were wrong (not bright enough — see secondary button in screenshot below).
Before:
After:
> Fix alignment when heading is omitted

- .changeset/cuddly-forks-own.md
- packages/combobox/src/combobox.tsx
This is a small PR to fix some [variable shadowing](https://en.wikipedia.org/wiki/Variable_shadowing) in the `useAwaitableItems` hook.
I've snuck in a few other minor changes:
- ComboboxProps are now sorted alphabetically
- Props on the ReactSelect component are now sorted alphabetically
- Overrides have had their names shorted to match the prop name for React Select
> Tidy up combobox
